[WIP] Route 53 API
Kuadrant/kuadra pull request #36
Opened 2024-03-25 14:29 UTC by ehearneRedHat

Currently a work in progress.

### Changes made:
- Created Route 53 API
- Added additional AWS Interfaces for Route 53
- Partially implemented method signatures from interfaces as functions for Route 53 Client

2024-03-25 16:26 UTC, ehearneRedHat commented
### To Do List (after feedback from @R-Lawton )

- [ ] Set up development environment for Route 53 API in the operator by implementing (in a simple manner) the code required to get the controller up and running, and therefore test functionality of the controller.
- [ ] In order to test the functionality of the controller, test each function as it is written. This allows for a more simpler and incremental approach. Try to test the CreateHostedZone() first without worrying about the current checks for root domain, for example.
- [ ] For the IsRootDomain() function, add more params to the function, such as the rootDomain itself to test if exists. The root domain can be specified in the CRD sample for the Route 53 controller.

2024-04-04 09:08 UTC, ehearneRedHat commented
@R-Lawton it is time... :) 

If you could review my PR that would be great!

2024-04-12 10:24 UTC, R-Lawton requested changes

2024-04-12 10:24 UTC, R-Lawton commented on internal/controller/route53_controller.go
> +	if !route53.Status.HostedZoneCreated {
I dont see a scenario where this if would kick in, if the route53 cr has been deleted but not fulling yet it will always have a deletion timestamp and go into the above if statement

2024-04-12 10:24 UTC, R-Lawton commented on internal/controller/route53_controller.go
> +		log.V(1).Info("created hosted zone", "domainName", route53.Spec.DomainName)
The log verbosity is showing as DEBUG even tho its as info, removing the number of the verbosity should change this

2024-04-12 10:24 UTC, R-Lawton commented on internal/controller/route53_controller.go
> +		log.V(1).Info("created hosted zone", "domainName", route53.Spec.DomainName)
This is in a few places

2024-04-12 10:24 UTC, R-Lawton commented on internal/controller/route53_controller.go
> +	if err := r.Get(ctx, req.NamespacedName, &route53); err != nil {
```suggestion
	if err := r.Get(ctx, req.NamespacedName, &route53); err != nil {
	    log.info("error getting the route53 cr",err)
	
```

2024-04-12 10:24 UTC, R-Lawton commented on pkg/aws/route53_client.go
> +		log.Printf("Failed to grab hosted zones from AWS. Here's why: %v", err)
I would change the "here why" to "error:" its more inline with best practices also the best practice for log messages is they start with lowercase and don't end in punctuation. [It allows them be combined](https://docs.sourcegraph.com/dev/background-information/languages/go_errors#:~:text=Idiomatic%20error%20messages%20in%20Go,%2C%20an%20unexported%20package%20constant).)

2024-04-12 10:33 UTC, R-Lawton commented
@dlaw4608 Can you give this PR a gander too, please

2024-04-12 11:31 UTC, ehearneRedHat commented on internal/controller/route53_controller.go
> +		log.V(1).Info("created hosted zone", "domainName", route53.Spec.DomainName)
@R-Lawton I see what you mean, it does appear as DEBUG

```
2024-04-12T12:23:30+01:00	DEBUG	created hosted zone	{"controller": "route53", "controllerGroup": "kuadra.kuadrant.io", "controllerKind": "Route53", "Route53": {"name":"route53-sample","namespace":"default"}, "namespace": "default", "name": "route53-sample", "reconcileID": "83a4d5e6-c248-41bc-969c-aef13f7fc30b", "domainName": "ehearne.sampledomain.com"}
```

I will go ahead and make changes wherever I can find log.V(1).Info() . :smile:

2024-04-12 11:35 UTC, ehearneRedHat commented on internal/controller/route53_controller.go
> +		log.V(1).Info("created hosted zone", "domainName", route53.Spec.DomainName)
Changes have been made, and the level of log is now INFO for those messages.

```
2024-04-12T12:33:20+01:00	INFO	deleted hosted zone	{"controller": "route53", "controllerGroup": "kuadra.kuadrant.io", "controllerKind": "Route53", "Route53": {"name":"route53-sample","namespace":"default"}, "namespace": "default", "name": "route53-sample", "reconcileID": "a2fc599c-8eed-4ea0-b8f0-50ad590bc59a", "domainName": "ehearne.sampledomain.com"}
```

2024-04-12 11:39 UTC, R-Lawton commented on internal/controller/route53_controller.go
> +	if !route53.Status.HostedZoneCreated {
Nevermind i cant read  🤦‍♀️

2024-04-12 11:41 UTC, ehearneRedHat commented on internal/controller/route53_controller.go
> +	if !route53.Status.HostedZoneCreated {
Resolved as reconciler is able to pick up deletion timestamp and discern when to and when not to allow a CRUD operation.

```
evanhearne@fedora:~/projects/github/kuadrant/kuadra$ kubectl apply -f config/samples/kuadra_v1_route53.yaml
Warning: Detected changes to resource route53-sample which is currently being deleted.
route53.kuadra.kuadrant.io/route53-sample unchanged

# It won't allow another CRUD operation until reconciliation... 

evanhearne@fedora:~/projects/github/kuadrant/kuadra$ kubectl apply -f config/samples/kuadra_v1_route53.yaml
route53.kuadra.kuadrant.io/route53-sample created
```

2024-04-12 11:47 UTC, ehearneRedHat commented on internal/controller/route53_controller.go
> +	if err := r.Get(ctx, req.NamespacedName, &route53); err != nil {
Added log.Error() instead - would that be fine ?

2024-04-12 11:52 UTC, R-Lawton commented on internal/controller/route53_controller.go
> +	if err := r.Get(ctx, req.NamespacedName, &route53); err != nil {
yeah thats better actually

2024-04-12 11:58 UTC, ehearneRedHat commented on pkg/aws/route53_client.go
> +		log.Printf("Failed to grab hosted zones from AWS. Here's why: %v", err)
@R-Lawton I will go ahead and make those changes.

2024-04-12 13:20 UTC, R-Lawton commented on pkg/aws/route53_client.go
> +		log.Printf("Failed to grab hosted zones from AWS. error: %v", err)
Can you make these lower case to

2024-04-12 13:33 UTC, ehearneRedHat commented on pkg/aws/route53_client.go
> +		log.Printf("Failed to grab hosted zones from AWS. error: %v", err)
No worries, done!

2024-04-12 13:58 UTC, R-Lawton commented
lgtm nice job Evan

2024-04-29 16:07 UTC, dlaw4608 approved these changes
Looks really cool Evan, great feature added +1

2024-04-29 16:41 UTC, R-Lawton approved these changes

2024-04-29 16:41 UTC, merged